---
- name: "Deploy bitbucket"
  hosts: bitbucket
  roles:
    - { role: common,       tags: common      }
    - { role: nginx,        tags: nginx       }
    - { role: postgres,     tags: postgres    }
    - { role: bitbucket,    tags: bitbucket   }
