---
- name: "Deploy jira core"
  hosts: jira
  roles:
    - { role: common,       tags: common      }
    - { role: nginx,        tags: nginx       }
    - { role: postgres,     tags: postgres    }
    - { role: jira,         tags: jira        }
